name: Auto Merge Dependabot

on:
  pull_request_target:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  automerge:
    runs-on: self-hosted

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3
