name: Merge me!

on:
  workflow_run:
    types:
      - completed
    workflows:
      - Continuous Integration

jobs:
  merge-me:
    name: Merge me!
    runs-on: self-hosted
    steps:
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
